igraph::V                -> V
igraph::E                -> E
igraph::edge_attr        -> eattr
igraph::`edge_attr<-`    -> `eattr<-`
igraph::vertex_attr      -> vattr
igraph::`vertex_attr<-`  -> `vattr<-`
igraph::as_adj           -> as_adj
igraph::induced_subgraph -> subg
igraph::layout_with_fr   -> layout_with_fr
igraph::layout_in_circle -> layout_in_circle
igraph::layout_nicely    -> layout_nicely
igraph::graph_from_adjacency_matrix -> adj_to_g
igraph::make_ego_graph   -> ego_graph
igraph::is_directed      -> is_directed
igraph::modularity       -> modularity
igraph::crossing         -> crossing
igraph::is_weighted      -> is_weighted
igraph::membership       -> membership